SELECT * FROM DEV;

CREATE TABLE DEV (
  DEVNO NUMBER PRIMARY KEY,
  DEVNAME VARCHAR2(50) NOT NULL,
  DEVAGE NUMBER,
  DEVEMAIL VARCHAR2(100) NOT NULL,
  DEVGENDER CHAR(1) CHECK(DEVGENDER IN ('M','F')),
  DEVLANG VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_DEV_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;
